<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="UploadService" targetNamespace="http://schemas.ontariomd.com/hrm/upload" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.ontariomd.com/hrm/upload" xmlns:ns1="http://schemas.ontariomd.com/hrm/upload/type" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://schemas.ontariomd.com/hrm/upload/type" schemaLocation="UploadService_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="uploadMessageResponse">
    <wsdl:part name="uploadMessageResponse" element="ns1:uploadMessageResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="uploadMessage">
    <wsdl:part name="uploadMessageRequest" element="ns1:uploadMessageRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="UploadServiceException">
    <wsdl:part name="UploadServiceException" element="ns1:UploadServiceException">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="UploadService">
    <wsdl:operation name="uploadMessage">
      <wsdl:input name="uploadMessage" message="tns:uploadMessage">
    </wsdl:input>
      <wsdl:output name="uploadMessageResponse" message="tns:uploadMessageResponse">
    </wsdl:output>
      <wsdl:fault name="UploadServiceException" message="tns:UploadServiceException">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="UploadServiceServiceSoapBinding" type="tns:UploadService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="uploadMessage">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="uploadMessage">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="uploadMessageResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="UploadServiceException">
        <soap:fault name="UploadServiceException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="UploadService">
    <wsdl:port name="UploadServicePort" binding="tns:UploadServiceServiceSoapBinding">
      <soap:address location="http://localhost:9090/UploadServicePort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
